name: Go CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

jobs:
  go-checks:
    name: Run Go Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Download Go modules
        run: go mod download

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger docs
        run: swag init -g cmd/api/main.go

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
        env:
          GOLANGCI_LINT_INSTALL_FROM: binary

      - name: Build code
        run: go build ./...

      - name: Run gofmt
        run: |
          UNFORMATTED=$(gofmt -l .)
          if [ -n "$UNFORMATTED" ]; then
            echo "Files not formatted:"
            echo "$UNFORMATTED"
            exit 1
          fi

      - name: Run go vet
        run: go vet ./...

      #- name: Run golangci-lint
      #  run: golangci-lint run ./...

      - name: Run go test
        run: go test -v ./...
